# _config.yml

title: Philip White

remote_theme: "mmistakes/minimal-mistakes"

author:
  name: "Philip White"
  avatar: /assets/images/headshot_background.jpg

plugins:
  - jekyll-include-cache

include:
  - _pages