# _config.yml

title: Philip White

remote_theme: "mmistakes/minimal-mistakes"

author:
  avatar: /assets/images/headshot_background.jpg
  bio: |
    Assistant Professor
    Department of Statistics 
    School of Medicine 
    Brigham Young University  

plugins:
  - jekyll-include-cache

include:
  - _pages