# _config.yml

title: Philip White

remote_theme: "mmistakes/minimal-mistakes"

author:
  avatar: /assets/images/headshot_background.jpg
  bio: |
    Assistant Professor<br>
    Brigham Young University<br>
    Department of Statistics<br>
    School of Medicine

plugins:
  - jekyll-include-cache

include:
  - _pages